[package]
name = "amber-msgs-metaio"
version.workspace = true
edition.workspace = true

[dependencies]
gstd.workspace = true
gmeta.workspace = true
parity-scale-codec.workspace = true
scale-info.workspace = true